#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'vim'
cookbook 'editor'
cookbook 'git'
cookbook 'build-essential'
cookbook 'myzsh',
	:github => 'dan9186/myzsh-cookbook'
